from typing import Dict
from datetime import datetime
import logging

logger = logging.getLogger(__name__)

def create_event_card(answer_data: Dict) -> Dict:
    """Create an event card from the answer data."""
    try:
        # Extract relevant information from the answer
        description = answer_data.get('answer', '')
        question = answer_data.get('question', '')
        
        # Determine card type based on question content
        card_type = 'memory'  # Default type
        
        if 'parents' in question.lower() or 'siblings' in question.lower():
            card_type = 'person'
        elif 'place' in question.lower() or 'where' in question.lower():
            card_type = 'place'
            
        # Create the card
        card = {
            'title': question,
            'description': description,
            'type': card_type,
            'date': datetime.now().isoformat(),
            'image_url': None  # This would be generated by an image service
        }
        
        return card
    except Exception as e:
        logger.error(f"Error creating event card: {str(e)}")
        return None 